### PR TITLE
pretty sure... fixed dynamic and removed some completley useless stuff

### PR DESCRIPTION
**Pull request by Coding4Hours**

### CODE REVIEW

**Comment by not-amplify** [comment]
This would break some of our speed stuff remove our  UV and break other things

**Comment by not-amplify** [comment]
Don’t plan to merge

**Comment by Coding4Hours** [comment]
wdym

**Comment by Coding4Hours** [comment]
it would help

**Comment by Coding4Hours** [comment]
less files
to load

**Comment by lucid-devv** [comment]
Less files that you MAY think are **not** important that actually are important. You deleted UV which is one of the key components to making our site fast.

**Comment by lucid-devv** [comment]
And removed/changed files that actually messed up other files.

**Pull request closed without merging**
